/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppBar: typeof import('./src/components/Layout/AppBar.vue')['default']
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    Content: typeof import('./src/components/Layout/Content.vue')['default']
    ContentPage: typeof import('./src/components/Layout/ContentPage.vue')['default']
    DefaultButton: typeof import('./src/components/DefaultButton.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navigation: typeof import('./src/components/Layout/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    TableCustom: typeof import('./src/components/TableCustom.vue')['default']
  }
}
